#!/dis/sh

(file section S1 S2 S3 S4 S5 S6 S7 S8 S9) = $*

pathfile='/lib/aide/'^$file

if {no $S1} {S1=''}
if {no $S2} {S2=''}
if {no $S3} {S3=''}
if {no $S4} {S4=''}
if {no $S5} {S5=''}
if {no $S6} {S6=''}
if {no $S7} {S7=''}
if {no $S8} {S8=''}
if {no $S9} {S9=''}

echo '|aide' $file $section $S1 $S2 $S3 $S4 $S5 $S6 $S7 $S8 $S9 | sed 's, *$,,g'

if {no $section} {
	apply {echo '|aide '^$file^' '^$1 | sed 's, *$,,g'} `{grep '^[^: ]+:$' $pathfile | sed 's :$  '}
} {
	sed -n '/^'^$section^':$/,/^$/p' $pathfile | sed 's \$\$1 '^$S1^' g;s \$\$2 '^$S2^' g;s \$\$3 '^$S3^' g;s \$\$4 '^$S4^' g;s \$\$5 '^$S5^' g;s \$\$6 '^$S6^' g;s \$\$7 '^$S7^' g;s \$\$8 '^$S8^' g;s \$\$9 '^$S9^' g;' | sed 's, *$,,g'
}
