#!/dis/sh
context = $*
if {no $context} {
	next = 1
	past = `{sed -n '1s, .*,,p' /tmp/switches}
} {
	next = 0
}

apply {
	time = $1
	if {~ $next 1} {
		echo `{fc $time $past -}
		next = 0
	}
	c = `{grep $time /tmp/switches | sed 's,.* ,,'}
	if {or {no $context} {~ $"c $"context}} {
		past = $time
		next = 1
	}
} `{cat /tmp/switches | sed 's, .*,,'}

exit 0
