#!/dis/sh
load std
load arg

self = $0
args = $*
noremote = 0
(arg 
	r  {noremote = 1}
	'*' {echo $self: warning: unknown option $opt}
	- $args
)
cmd = $*

if {no $cmd} {cmd = pwd}
cwd = `{pwd}

if {and {~ $cwd '*/tmg/*'} {~ $noremote 0}} {
	host = `{echo $cwd | sed 's .*/tmg/([^/]+)/.* \1 ;s .*/tmg/([^/]+)$ \1 '}
	dir = `{echo $cwd | sed 's .*/tmg/([^/]+)(/.*) \2 ;s .*/tmg/([^/]+)$ / '}
	os -d^`{osdir} ssh $host cd $dir ';' $cmd
} {
	os -d^`{osdir} $cmd
}
