#!/dis/sh
load std
load arg

self = $0
args = $*
noremote = 0
(arg 
	r  {noremote = 1}
	'*' {echo $self: warning: unknown option $opt}
	- $args
)
cmd = $*

if {no $cmd} {cmd = pwd}
cwd = `{pwd}

if {and {~ $cwd '*/cx/*'} {~ $noremote 0}} {
	host_name = `{echo $cwd | sed 's .*/cx/([^/]+)/.* \1 ;s .*/cx/([^/]+)$ \1 '}
	host_dir = `{echo $cwd | sed 's .*/cx/([^/]+)(/.*) \2 ;s .*/cx/([^/]+)$ / '}
	host_fqdn = `{os mount | grep $host_name | sed 's ^.*@  ;s :/.*$  '}
	os -d^`{osdir} ssh -l jason.catena $host_fqdn cd $host_dir ';' $cmd
} {
	os -d^`{osdir} $cmd
}
