#!/dis/sh
if {no $1} {
	dir = $emuroot^`{pwd}
} {
	dir = $emuroot^$1
}

echo $dir | sed '
s,^/usr/inferno/github,/usr/coinferno/github,
s,^/usr/inferno/gitlab,/usr/coinferno/gitlab,
s,^/usr/inferno/gitcx,/usr/coinferno/gitcx,
s,^/usr/inferno/n/local,,
'
