#!/dis/sh
load std

pid=`{echo ${pid}}
if {ftest -r watch.out.old.$pid} {rm watch.out.old.$pid}
touch watch.out.old.$pid

while {ftest -r watch.out.old.$pid} {
	d=`{pwd}
	$* > $d/watch.out.new.$pid >[2=1]
	cd $d
	if {! cmp watch.out.old.$pid watch.out.new.$pid} {
		date >> watch.log.$pid
		diff watch.out.old.$pid watch.out.new.$pid >> watch.log.$pid
		echo >> watch.log.$pid
	}
	sleep 2
	mv watch.out.new.$pid watch.out.old.$pid
}
