#!/dis/sh
load std

if {~ $1 -l} {(l cmd) = $*} {cmd = $*}
if {no $cmd} {cmd = pwd}
cwd = `{pwd}

if {~ $cwd '*/netco/*'} {
	host = `{echo $cwd | sed 's,.*/netco/([^/]+)/.*,\1,;s,.*/netco/([^/]+)$,\1,'}
	dir = `{echo $cwd | sed 's,.*/netco/([^/]+)(/.*),\2,;s,.*/netco/([^/]+)$,/,'}
	os -d^`{osdir} ssh $host cd $dir ';' $cmd
} {
	os -d^`{osdir} $cmd
}

if {! ~ $l -l} {log host $*}
exit 0
