#!/dis/sh
load std

if {~ $1 '[0-9]*'} {
	(section topics) = $*
	apply {
		topic = $1
		if {! plumb $topic^'('^$section^')'} {
			man2txt /man/$section/$topic
		}
	} $topics
	log lman $section $topic
} {
	topics = $*
	apply {
		topic = $1
		if {! lookman $topic | sed 's,^man ,lman ,'} {
			if {ftest -e /man/1/$topic} {
				if {! wm/man -f /man/1/$topic} {
					man -f /man/1/$topic
				}
			}
		}
	} $topics
}
