#!/dis/sh
if {no $1} {
	dir = $emuroot^`{pwd}
} {
	dir = $emuroot^$1
}
echo $dir | sed '
s,^/usr/inferno/getco,/usr/coinferno/getco,
s,^/usr/inferno/gitco,/usr/coinferno/gitco,
s,^/usr/inferno/github,/usr/coinferno/github,
s,^/usr/inferno/gitorious,/usr/coinferno/gitorious,
s,^/usr/inferno/netco,/usr/coinferno/netco,
s,^/usr/inferno/n/local,,
'
