#!/dis/sh
if {no $*} {
	fn fmttime {
		time = $1
		echo `{date $time} `{grep $time /tmp/switches | sed 's,.* ,,'}
	}
	apply {fmttime $1} `{sed 's, .*,,' /tmp/switches}
	exit 0
}

fn delerrfile {
	tag = $1/tag
	pf = `{cat $tag | sed 's, .*,,'}
	p = `{echo $pf | sed 's,/?[^/]+$,,;s,^$,.,'}
	f = `{basename $pf}
	if {and {~ $f '*+Errors'} {ftest -e $pf}} {rm $pf}
}

fn delwin {
	echo put > $1/ctl
	echo del > $1/ctl
}

apply {delerrfile $1; delwin $1} `{ls -d /mnt/acme/[0-9]*}
cat /tmp/Aide |  fuzzy $*
echo `{date -n }$* >> /tmp/switches
tmpaide
